name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Install CFEngine community for tests
      run: |
        pipx install cf-remote
        cf-remote install --clients localhost --edition community
    - name: Run make check for linting, formatting and tests
      run: make check
