name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Install python tools
      run: pipx install flake8 pyright black pyflakes pytest cfbs cfengine
    - name: Check the status with cfbs
      run: cfbs status
    - name: Validate with cfbs
      run: cfbs validate
    - name: Check the formatting
      run: cfbs --check pretty ./cfbs.json
    - name: Linting python code
      run: ./ci/linting.sh
    - name: Run promise type tests
      run: pytest promise-types/ -v
    - name: Lint policy with CFEngine CLI
      run: cfengine lint --strict no ./
